#!/bin/bash

if [ -z "$4" ]; then
    echo
    echo "Script for converting mCoNLL-09.EXT parser output to mCoNLL format "
    echo "Usage: ./ext2conll_2009 project_path test.conll  parser_res.conll.ext  parser_res.conll"
    echo "-  project_path"
    echo "   path to the parsing project"
    echo "-  test.conll"
    echo "   Original test mCoNLL-08 file in utf-8 (as before processing with ./prepare_data or"
    echo "   ./convert_to_conll_ext) - blind or with gold standard dependency structure"
    echo "-  parser_res.conll.ext"
    echo "   Parser output on this file in CoNLL.ext format"
    echo "-  parser_res.conll"
    echo "   Parser output converted to CoNLL format and deprojectivized will be produced by the script"
    echo "   Additionally parser_res.conll.proj will contain the parser output in CoNLL format"
    echo "   but without the projectivization"
    exit 1
fi

PROJECT_PATH=$1

TEST_IN_FILE=$2
TEST_IN_FILE_SIMPLE=${TEST_IN_FILE##*/}

PARSER_RES_FILE=$3
PARSER_RES_FILE_SIMPLE=${PARSER_RES_FILE##*/}

PARSER_CONLL=$4
PARSER_CONLL_SIMPLE=${PARSER_CONLL_SIMPLE##*/}
SCRIPT_BASE_PATH=${0%/*}

#produce blind file from TEST_IN_FILE if it is not blind 
HEAD_FIELD=`head -n 1 $TEST_IN_FILE | awk '{print  $9}'`

#9	learning	0	0	learn	832	VBG	20	VBG	20	_	1	1	0	0	0	ROOT	-1	learn.01	0	8	A0	0	10	A1	1

#  deprojectivization
if [ ! $HEAD_FIELD == "" ] 
then
    cat $TEST_IN_FILE | awk '{if ($0 == "") printf "\n"; else printf "%d\t%s\t%s\t%s\t%s\t%s\n", $1, $2, $3, $5, $6, $7}' \
        > $$.$TEST_IN_FILE_SIMPLE.blind
else
    cp $TEST_IN_FILE $$.$TEST_IN_FILE_SIMPLE.blind
fi

#produce predictions form parser_res.conll.ext
cat $PARSER_RES_FILE  | awk '{if ($0 == "")  printf "\n";  else  printf "%d\t%s\t_\t_\n", $16, $17}' \
    > $$.$PARSER_RES_FILE_SIMPLE.preds

#produce arg structures from parser_res.conll.ext
cat $PARSER_RES_FILE  |  awk \
'{\
    if ($0 == "")  \
        printf "\n";\
    else {\
        printf "%s", $19; \
        for (i = 21; i <= NF; i++) {  \
            if ((i - 21) % 3 == 0 || (i - 21) % 3 == 1) \
                printf "\t%s", $i;\
        } \
        printf "\n" \
    }  \
}' > $$.$PARSER_RES_FILE_SIMPLE.srl_preds


# produce non deprojectivized conll format
paste  $$.$TEST_IN_FILE_SIMPLE.blind $$.$PARSER_RES_FILE_SIMPLE.preds | awk '{if ($0 ~ "^[[:space:]]$") printf "\n"; else printf "%s\n", $0 }' \
    >  $PARSER_CONLL.proj

#deprojectivize  
mv $PARSER_CONLL.proj $PARSER_CONLL.proj.TMP
perl -wln -e 's/^\s+$//; print;' $PARSER_CONLL.proj.TMP > $PARSER_CONLL.proj
rm $PARSER_CONLL.proj.TMP
echo "java -jar $SCRIPT_BASE_PATH/pseudoproj/proj2NonProj.jar  $PARSER_CONLL.proj $PROJECT_PATH/deps.nonproj 1 conll UTF-8"
java -jar $SCRIPT_BASE_PATH/pseudoproj/proj2NonProj.jar  $PARSER_CONLL.proj $PROJECT_PATH/deps.nonproj 1 conll UTF-8
cat deprojectivized.conll |  awk '{if ($0 == "")  printf "\n";  else  printf  "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n", $1, $2, $3, $4, $5, $6, $7, $8}' > $PARSER_CONLL.no_srl

#join with srl
paste $PARSER_CONLL.no_srl $$.$PARSER_RES_FILE_SIMPLE.srl_preds | awk '{if ($0 ~ "^[[:space:]]$") printf "\n"; else printf "%s\n", $0 }' > $PARSER_CONLL

mv $PARSER_CONLL $PARSER_CONLL.TMP
perl -wln -e 's/^\s+$//; print;' $PARSER_CONLL.TMP > $PARSER_CONLL
rm $PARSER_CONLL.TMP

echo "result saved in: $PARSER_CONLL"

#rm -f  $$.$PARSER_RES_FILE_SIMPLE.preds $$.$TEST_IN_FILE_SIMPLE.blind  $PARSER_CONLL.no_srl $$.$PARSER_RES_FILE_SIMPLE.srl_preds deprojectivized.conll

#validate 
#python $SCRIPT_BASE_PATH/validateFormat.py -t system $PARSER_CONLL
#if [ ! $? -eq 0 ] 
#then
#    echo Failed format validation. Something is wrong...
#else 
#    echo Format validation succeeded.
#fi



echo Done
